name: Publish Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build

      - name: Login to docker hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} --build-arg NAME=siam --tag ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-server:latest

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-server:latest
