name: Publish Docker Image

on:
  push:
    branches: ["main"]

env:
  DATABASE_URL: postgresql://postgres:ta81TSMaktITp5k5@db.lvvqrihhvntnibjwvbly.supabase.co:5432/postgres
  CHK: yes bro its working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: yarn install

      - name: Build Application
        run: yarn build

      - name: Login to docker hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-server:latest

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ocean-harbor-server:latest
